name: conll2003_ablation_wordlevel_s43
dataset_config: configs/dataset/conll2003_autodl.yaml
model_config: configs/model/bilstm_crf_glove.yaml
embeddings:
  glove_dir: /root/autodl-tmp/EdgeFS_NER/data/embeddings
  dim: 100
train:
  epochs: 30
  batch_size: 32
  lr: 0.001
  weight_decay: 0.0001
  max_len: 128
  max_word_len: 20
  device: cuda
  seed: 43
  output_dir: /root/autodl-tmp/EdgeFS_NER/outputs/runs/conll2003_ablation_wordlevel_s43
  lr_scheduler: plateau
  scheduler_patience: 3
  scheduler_factor: 0.5
