name: ontonotes_tinybert
dataset_config: configs/dataset/ontonotes_autodl.yaml
model_config: configs/model/bert_crf_tiny.yaml
train:
  epochs: 5
  batch_size: 16
  lr: 0.00005
  weight_decay: 0.01
  max_len: 128
  device: cuda
  seed: 42
  output_dir: /root/autodl-tmp/EdgeFS_NER/outputs/runs/ontonotes_tinybert
  lr_scheduler: plateau
  scheduler_patience: 2
  scheduler_factor: 0.5
